name: deploy lambda lambda_docker

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  deploy:
    environment:
      name: ${{ inputs.environment }}

    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.FETCH_TOKEN }}

      - name: deploy
        env:
          ACCOUNT_FAMILY: ${{ vars.ACCOUNT_FAMILY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVICE_NAME: ${{ vars.SERVICE_NAME }}
          GO_TO_DIR: ${{ vars.GO_TO_DIR }}
          CI_JOB_TOKEN: ${{ secrets.FETCH_TOKEN }}
          SERVICE_NAME_ENV_SUFIX: ${{ vars.SERVICE_NAME_ENV_SUFIX }}

        run: |
          echo "Iniciando deploy da Lambda..."
          export CI_COMMIT_BRANCH=${GITHUB_REF_NAME}
          echo "Branch: ${CI_COMMIT_BRANCH}"

          export CI_PROJECT_NAME=$(echo "${GITHUB_REPOSITORY}" | awk -F / '{print $2}')
          echo "Nome do projeto: ${CI_PROJECT_NAME}"

          echo "Instalando AWS CLI..."
          if [ -x "$(command -v apt-get)" ]; then
            apt-get update && apt-get install -y awscli
          fi

          if [ -x "$(command -v apk)" ]; then
            apk add aws-cli
          fi

          echo "Configurando credenciais AWS..."
          # BEGIN carregando chaves

          mkdir ~/.aws
          touch ~/.aws/credentials

          echo "Obtendo credenciais do SSM Parameter Store..."
          aws ssm get-parameters --names "/cicd/${ACCOUNT_FAMILY}/credentials" --with-decryption --query "Parameters[0].Value" --output text > ~/.aws/credentials

          if [ "$(cat ~/.aws/credentials)" == "null" ] && [ "$(cat ~/.aws/credentials)" == "None" ]; then
            echo "ERRO: Credenciais AWS não encontradas."
            echo "ERRO: O ambiente está configurado corretamente?"
            echo "ERRO: Verifique a variável de ambiente ACCOUNT_FAMILY"
            exit 1
          fi

          export AWS_PROFILE=${CI_COMMIT_BRANCH}
          echo "AWS Profile configurado: ${AWS_PROFILE}"

          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY

          echo "Configurando região AWS..."
          export region_candidate=$(aws ssm get-parameters --names "/cicd/account/region/${CI_COMMIT_BRANCH}" --with-decryption --query "Parameters[0].Value" --output text)

          if [ "${region_candidate}" != "null" ] && [ "${region_candidate}" != "None" ]; then
            export AWS_DEFAULT_REGION=${region_candidate}
            echo "Região específica da branch encontrada: ${AWS_DEFAULT_REGION}"
          else
            export region_candidate=$(aws ssm get-parameters --names "/cicd/account/region" --with-decryption --query "Parameters[0].Value" --output text)
            if [ "${region_candidate}" != "null" ] && [ "${region_candidate}" != "None" ]; then
              export AWS_DEFAULT_REGION=${region_candidate}
              echo "Usando região padrão: ${AWS_DEFAULT_REGION}"
            fi
          fi

          # END carregando chaves

          echo "Configurando variáveis do serviço..."
          if [ -z "${GO_TO_DIR}" ]; then
              export GO_TO_DIR="."
              echo "Usando diretório padrão: ${GO_TO_DIR}"
          fi

          if [ -z "${SERVICE_NAME}" ]; then
              export SERVICE_NAME=${CI_PROJECT_NAME}
              echo "Usando nome do projeto como nome do serviço: ${SERVICE_NAME}"
          fi

          if [ "${SERVICE_NAME_ENV_SUFIX}" == "true" ]; then
              export SERVICE_NAME="${SERVICE_NAME}-${CI_COMMIT_BRANCH}"
              echo "Nome do serviço com sufixo de ambiente: ${SERVICE_NAME}"
          fi

          echo "Obtendo endereço do registro ECR..."
          export ECR_REGISTRY_ADDRESS=$(aws ecr describe-repositories | grep repositoryUri | awk '{print $2}' | sed -e 's/\"\(.*\)\"\,/\1/' | grep ${SERVICE_NAME})
          echo "Endereço do registro ECR: ${ECR_REGISTRY_ADDRESS}"

          echo "Fazendo login no ECR..."
          aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY_ADDRESS}

          export TIMESTAMP=$(date +%s)
          echo "Timestamp da build: ${TIMESTAMP}"

          echo "Mudando para o diretório do projeto: ${GO_TO_DIR}"
          cd ${GO_TO_DIR}

          echo "Construindo imagem Docker..."
          docker build -t "${ECR_REGISTRY_ADDRESS}:latest" --build-arg CI_JOB_TOKEN="${CI_JOB_TOKEN}" .

          echo "Criando tag com timestamp..."
          docker image tag "${ECR_REGISTRY_ADDRESS}:latest" "${ECR_REGISTRY_ADDRESS}:${TIMESTAMP}"

          echo "Enviando imagens para o ECR..."
          docker push ${ECR_REGISTRY_ADDRESS}:${TIMESTAMP} &
          docker push ${ECR_REGISTRY_ADDRESS}:latest &

          wait
          echo "Imagens enviadas com sucesso"

          echo "Fazendo logout do ECR..."
          docker logout $ECR_REGISTRY_ADDRESS

          echo "Aguardando propagação das imagens..."
          sleep 5

          echo "Atualizando função Lambda..."
          aws lambda update-function-code --function-name ${SERVICE_NAME} --image-uri "${ECR_REGISTRY_ADDRESS}:latest"
          echo "Deploy concluído com sucesso!"