name: deploy lambda docker

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  deploy:
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.FETCH_TOKEN }}

      - name: Checkout Pipeline Scripts
        uses: actions/checkout@v4
        with:
          repository: lugui-co/infra-github-pipelines
          ref: production
          path: infra-github-pipelines
          token: ${{ secrets.FETCH_TOKEN }}

      - name: deploy
        env:
          ACCOUNT_FAMILY: ${{ vars.ACCOUNT_FAMILY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVICE_NAME: ${{ vars.SERVICE_NAME }}
          GO_TO_DIR: ${{ vars.GO_TO_DIR }}
          CI_JOB_TOKEN: ${{ secrets.FETCH_TOKEN }}
          SERVICE_NAME_ENV_SUFIX: ${{ vars.SERVICE_NAME_ENV_SUFIX }}
        run: |
          echo "Starting Lambda deployment..."
          export CI_COMMIT_BRANCH=${GITHUB_REF_NAME}
          export CI_PROJECT_NAME=$(echo "${GITHUB_REPOSITORY}" | awk -F / '{print $2}')

          # Install AWS CLI if needed
          if [ -x "$(command -v apt-get)" ]; then
            sudo apt-get update && sudo apt-get install -y awscli
          fi
          if [ -x "$(command -v apk)" ]; then
            sudo apk add aws-cli
          fi

          # Source helper scripts
          source infra-github-pipelines/scripts/aws_setup.sh
          source infra-github-pipelines/scripts/docker_operations.sh
          source infra-github-pipelines/scripts/lambda_operations.sh

          # Setup AWS credentials
          setup_aws_credentials "${ACCOUNT_FAMILY}" "${CI_COMMIT_BRANCH}"

          # Setup Lambda environment
          setup_lambda_environment "${SERVICE_NAME}" "${CI_PROJECT_NAME}" "${CI_COMMIT_BRANCH}" "${SERVICE_NAME_ENV_SUFIX}"

          # Get ECR registry address
          ECR_REGISTRY_ADDRESS=$(get_ecr_registry "${SERVICE_NAME}")
          echo "ECR Registry Address: ${ECR_REGISTRY_ADDRESS}"

          # Build and push Docker image
          build_and_push_docker_image "${ECR_REGISTRY_ADDRESS}" "${CI_JOB_TOKEN}" "${GO_TO_DIR}"

          # Update Lambda function
          sleep 5
          update_lambda_function "${SERVICE_NAME}" "${ECR_REGISTRY_ADDRESS}:latest"
          
          echo "Deployment completed successfully!"