env:
  TERRAFORM_VERSION: "1.7.0"
  GO_VERSION: "1.20.4"
  PYTHON_VERSION: "pypy3.10"
  NODE_VERSION: "20.2.0"

setup:
  - name: checkout
    uses: actions/checkout@v4
    with:
      submodules: 'recursive'

  - name: setup_go
    uses: actions/setup-go@v4
    with:
      go-version: ${{ env.GO_VERSION }}

  - name: setup_python
    uses: actions/setup-python@v5
    with:
      python-version: ${{ env.PYTHON_VERSION }}

  - name: setup_node
    uses: actions/setup-node@v3
    with:
      node-version: ${{ env.NODE_VERSION }}

  - name: setup_terraform
    uses: hashicorp/setup-terraform@v3
    with:
      terraform_version: ${{ env.TERRAFORM_VERSION }} 